### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wermon1** [rogeraabbccdd/VRChat-MotionOSC#1]
I make the build but it not working are blank. Can you upload your build on release?

**Comment by rogeraabbccdd** [comment]
Hello, build script is not tested yet, but meanwhile you can use dev command to start the app.

**Comment by rogeraabbccdd** [comment]
Hello, build error is fixed in https://github.com/rogeraabbccdd/VRChat-MotionOSC/commit/88cf686a3ec2c544b88cec4adfc77a59d0ca70da
You can build and run the app successfully now.
